"""Render the documentation that has to stay true: the porting matrix.

A porting table is the first thing to rot. It is written once from what someone believed at
the time, and nothing afterwards fails when the runtime changes underneath it - which is
exactly how Pyodide's own documentation came to list four modules as removed that import
fine in 314.0.6.

So the matrix is not written, it is *rendered*, from the same registry the static analyser
and the runtime guards read. A test asserts the committed file matches this output, and the
characterisation tests re-measure the registry itself inside a real Pyodide. The chain from
"what the docs say" back to "what the runtime does" has no manual link in it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Final

from textual_wasm.bundler import PYODIDE_VERSION
from textual_wasm.substitutions import SUBSTITUTIONS, DetectionKind, Severity

if TYPE_CHECKING:
    from collections.abc import Iterable

    from textual_wasm.substitutions import Substitution

MATRIX_PATH: Final[str] = "docs/porting-matrix.md"
"""Where the rendered file lives, named here so the command and its test agree."""

GENERATED_NOTICE: Final[str] = (
    "<!-- Generated by `textual-wasm matrix`. Edit src/textual_wasm/substitutions.py. -->"
)

SEVERITY_HEADINGS: Final[dict[Severity, tuple[str, str]]] = {
    Severity.SILENT_WRONG: (
        "Silent and wrong",
        (
            "No exception is raised and the behaviour is wrong. This is the class Pyodide's own "
            "documentation does not cover, and the reason this project exists: every other kind "
            "of failure announces itself."
        ),
    ),
    Severity.FATAL: (
        "Fatal",
        (
            "Tears down the interpreter. Not a Python exception, so nothing catches it and "
            "nothing runs afterwards - including whatever you would have used to report it."
        ),
    ),
    Severity.LOUD_UNCLEAR: (
        "Loud but misleading",
        (
            "Raises, and the message sends you somewhere else - a symptom, a private module, or "
            "a generic errno rather than the actual constraint. `textual_wasm.diagnostics` "
            "rewrites exactly these."
        ),
    ),
    Severity.UNSUPPORTED: (
        "Absent",
        (
            "The module is not in the build, so it fails as an ordinary `ImportError` where you "
            "imported it. Listed because knowing *before* you deploy is the point."
        ),
    ),
    Severity.LOUD_CLEAR: (
        "Already clear",
        (
            "Raises with a message that says what is wrong and often how to fix it. Recorded so "
            "the runtime translator leaves them alone: replacing a good message with a generic "
            "one would be a regression."
        ),
    ),
}
"""Section title and preamble per severity, in the order the document presents them.

Ordered by how hard the failure is to diagnose rather than by how bad it sounds - a wrong
answer with no error costs more of an afternoon than a crash does.
"""


def _detection(substitution: Substitution) -> str:
    """How `textual-wasm doctor` spots this, in the reader's own vocabulary."""
    return ", ".join(
        f"`import {rule.target}`" if rule.kind is DetectionKind.IMPORT else f"`{rule.target}(...)`"
        for rule in substitution.detect
    )


def _cell(text: str) -> str:
    """Make a string safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def _rows(substitutions: Iterable[Substitution]) -> Iterable[str]:
    for substitution in substitutions:
        divergent = " **Differs between Node and a browser.**" if substitution.env_divergent else ""
        yield (
            f"| `{substitution.id}` | {_detection(substitution)} "
            f"| {_cell(substitution.observed)}{divergent} | {_cell(substitution.guidance)} |"
        )


def _section(severity: Severity) -> list[str]:
    """One severity class, or nothing at all if the registry has no entries in it."""
    entries = [s for s in SUBSTITUTIONS if s.severity is severity]
    if not entries:
        return []
    title, preamble = SEVERITY_HEADINGS[severity]
    return [
        f"## {title}",
        "",
        preamble,
        "",
        "| Capability | Detected as | What actually happens | What to do instead |",
        "|---|---|---|---|",
        *_rows(entries),
        "",
    ]


def render_matrix() -> str:
    """Render the porting matrix as Markdown.

    Returns:
        The whole document, ending in a newline.
    """
    lines = [
        GENERATED_NOTICE,
        "",
        "# Porting matrix",
        "",
        (
            f"What behaves differently under Pyodide {PYODIDE_VERSION}, measured rather than "
            "transcribed. Pyodide's own documentation lists `termios`, `fcntl`, `pty` and `tty` "
            "as removed; in this version all four import successfully. Every row below carries "
            "the snippet used to observe it, and a characterisation test re-runs those snippets "
            "inside a real Pyodide, so a runtime change fails the suite instead of quietly "
            "making this page wrong."
        ),
        "",
        (
            "Run `textual-wasm doctor <module:App>` to find these in your own source, with a "
            "`file:line` for each."
        ),
        "",
    ]
    for severity in SEVERITY_HEADINGS:
        lines += _section(severity)
    lines += [
        "## What is *not* here",
        "",
        "Things that work, and are worth naming because they are commonly assumed not to:",
        "",
        (
            "- `requests` and `httpx` work in a browser. Pyodide patches httpx, and bundled "
            "`urllib3` ships an Emscripten backend that routes through JSPI, a worker, or XHR. "
            "CORS applies, and timeouts, certificates and proxies are not controllable."
        ),
        (
            "- C-extension dependencies are no longer limited to what Pyodide bundles: a package "
            "can publish a `pyemscripten` wasm wheel to PyPI and `micropip` installs it. The "
            "inverse is the new constraint - a package that only exists as a Pyodide-bundled "
            "native wheel pins you to Pyodide's version of it."
        ),
        (
            "- `SharedArrayBuffer` does **not** unlock Python threads. It buys the interrupt "
            "buffer and urllib3's streaming worker. `@work(thread=True)` is unavailable in any "
            "configuration of this build."
        ),
        "",
    ]
    return "\n".join(lines) + "\n"
