"""Render the documentation that has to stay true: the porting matrix.

A porting table is the first thing to rot. It is written once from what someone believed at
the time, and nothing afterwards fails when the runtime changes underneath it - which is
exactly how Pyodide's own documentation came to list four modules as removed that import
fine in 314.0.6.

So the matrix is not written, it is *rendered*, from the same registry the static analyser
and the runtime guards read. A test asserts the committed file matches this output, and the
characterisation tests re-measure the registry itself inside a real Pyodide. The chain from
"what the docs say" back to "what the runtime does" has no manual link in it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Final

from textual_wasm.bundler import PYODIDE_VERSION
from textual_wasm.ecosystem import (
    LIBRARIES,
    MEASURED_AGAINST_TEXTUAL,
    MEASURED_AT,
    SUPPORT_ORDER,
    Support,
    with_support,
)
from textual_wasm.substitutions import SUBSTITUTIONS, DetectionKind, Severity

if TYPE_CHECKING:
    from collections.abc import Iterable

    from textual_wasm.ecosystem import Library
    from textual_wasm.substitutions import Substitution

MATRIX_PATH: Final[str] = "docs/porting-matrix.md"
"""Where the rendered file lives, named here so the command and its test agree."""

LIBRARIES_PATH: Final[str] = "docs/library-table.md"
"""Where the rendered add-on table lives. Included into `library-support.md`, which supplies
the context a generated document cannot write for itself."""

GENERATED_NOTICE: Final[str] = (
    "<!-- Generated by `textual-wasm matrix`. Edit src/textual_wasm/substitutions.py. -->"
)

LIBRARIES_NOTICE: Final[str] = (
    "<!-- Generated by `textual-wasm libraries`. Edit src/textual_wasm/ecosystem.py. -->"
)

SEVERITY_HEADINGS: Final[dict[Severity, tuple[str, str]]] = {
    Severity.SILENT_WRONG: (
        "Silent and wrong",
        (
            "No exception is raised and the behaviour is wrong. This is the class Pyodide's own "
            "documentation does not cover, and the reason this project exists: every other kind "
            "of failure announces itself."
        ),
    ),
    Severity.FATAL: (
        "Fatal",
        (
            "Tears down the interpreter. Not a Python exception, so nothing catches it and "
            "nothing runs afterwards - including whatever you would have used to report it."
        ),
    ),
    Severity.LOUD_UNCLEAR: (
        "Loud but misleading",
        (
            "Raises, and the message sends you somewhere else - a symptom, a private module, or "
            "a generic errno rather than the actual constraint. `textual_wasm.diagnostics` "
            "rewrites exactly these."
        ),
    ),
    Severity.UNSUPPORTED: (
        "Absent",
        (
            "The module is not in the build, so it fails as an ordinary `ImportError` where you "
            "imported it. Listed because knowing *before* you deploy is the point."
        ),
    ),
    Severity.LOUD_CLEAR: (
        "Already clear",
        (
            "Raises with a message that says what is wrong and often how to fix it. Recorded so "
            "the runtime translator leaves them alone: replacing a good message with a generic "
            "one would be a regression."
        ),
    ),
}
"""Section title and preamble per severity, in the order the document presents them.

Ordered by how hard the failure is to diagnose rather than by how bad it sounds - a wrong
answer with no error costs more of an afternoon than a crash does.
"""


def _detection(substitution: Substitution) -> str:
    """How `textual-wasm doctor` spots this, in the reader's own vocabulary."""
    return ", ".join(
        f"`import {rule.target}`" if rule.kind is DetectionKind.IMPORT else f"`{rule.target}(...)`"
        for rule in substitution.detect
    )


def _cell(text: str) -> str:
    """Make a string safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def _rows(substitutions: Iterable[Substitution]) -> Iterable[str]:
    for substitution in substitutions:
        divergent = " **Differs between Node and a browser.**" if substitution.env_divergent else ""
        yield (
            f"| `{substitution.id}` | {_detection(substitution)} "
            f"| {_cell(substitution.observed)}{divergent} | {_cell(substitution.guidance)} |"
        )


def _section(severity: Severity) -> list[str]:
    """One severity class, or nothing at all if the registry has no entries in it."""
    entries = [s for s in SUBSTITUTIONS if s.severity is severity]
    if not entries:
        return []
    title, preamble = SEVERITY_HEADINGS[severity]
    return [
        f"## {title}",
        "",
        preamble,
        "",
        "| Capability | Detected as | What actually happens | What to do instead |",
        "|---|---|---|---|",
        *_rows(entries),
        "",
    ]


def render_matrix() -> str:
    """Render the porting matrix as Markdown.

    Returns:
        The whole document, ending in a newline.
    """
    lines = [
        GENERATED_NOTICE,
        "",
        "# Porting matrix",
        "",
        (
            f"What behaves differently under Pyodide {PYODIDE_VERSION}, measured rather than "
            "transcribed. Pyodide's own documentation lists `termios`, `fcntl`, `pty` and `tty` "
            "as removed; in this version all four import successfully. Every row below carries "
            "the snippet used to observe it, and a characterisation test re-runs those snippets "
            "inside a real Pyodide, so a runtime change fails the suite instead of quietly "
            "making this page wrong."
        ),
        "",
        (
            "Run `textual-wasm doctor <module:App>` to find these in your own source, with a "
            "`file:line` for each."
        ),
        "",
    ]
    for severity in SEVERITY_HEADINGS:
        lines += _section(severity)
    lines += [
        "## What is *not* here",
        "",
        "Things that work, and are worth naming because they are commonly assumed not to:",
        "",
        (
            "- `requests` and `httpx` work in a browser. Pyodide patches httpx, and bundled "
            "`urllib3` ships an Emscripten backend that routes through JSPI, a worker, or XHR. "
            "CORS applies, and timeouts, certificates and proxies are not controllable."
        ),
        (
            "- C-extension dependencies are no longer limited to what Pyodide bundles: a package "
            "can publish a `pyemscripten` wasm wheel to PyPI and `micropip` installs it. The "
            "inverse is the new constraint - a package that only exists as a Pyodide-bundled "
            "native wheel pins you to Pyodide's version of it."
        ),
        (
            "- `SharedArrayBuffer` does **not** unlock Python threads. It buys the interrupt "
            "buffer and urllib3's streaming worker. `@work(thread=True)` is unavailable in any "
            "configuration of this build."
        ),
        "",
    ]
    return "\n".join(lines) + "\n"


SUPPORT_HEADINGS: Final[dict[Support, tuple[str, str]]] = {
    Support.VERIFIED: (
        "Works",
        (
            "Installed, imported, and at least one of the library's own widgets mounted and "
            "rendered inside a running Textual application under Pyodide. This is the only "
            "row class that means *works in a browser* - the three tiers below it are each a "
            "weaker claim, and they fail for unrelated reasons."
        ),
    ),
    Support.IMPORTS: (
        "Installs, not exercised",
        (
            "Installs and imports cleanly, but nothing could be mounted automatically: either "
            "it defines no Textual widget at all (a Rich renderable, a stylesheet) or every "
            "widget it defines needs constructor arguments a generic probe cannot invent. "
            "Absence of evidence, listed as such rather than rounded up to working."
        ),
    ),
    Support.TEXTUAL_CAP: (
        "Caps Textual below this build's",
        (
            f"Requires a Textual older than the {MEASURED_AGAINST_TEXTUAL} this project pins. "
            "The trap is that `micropip.install(name)` on its own **succeeds** - it quietly "
            "resolves Textual *down* to a version the cap allows, and you discover the "
            "downgrade later as missing widgets or changed APIs. None of this is a WASM "
            "constraint: the same cap binds a terminal install identically."
        ),
    ),
    Support.BLOCKED: (
        "Cannot be installed",
        (
            "The install fails under Pyodide. Read the middle column before assuming the "
            "reason is WebAssembly - three of these are ordinary dependency pins that would "
            "fail anywhere, and only the first is genuinely about a missing native build."
        ),
    ),
    Support.NOT_ON_PYPI: (
        "Not packaged",
        (
            "No distribution exists to install. `micropip` fetches from PyPI or a URL and has "
            "no path to a git repository, so the fix is to vendor the source into your own "
            "package - where the build ships it like any other module."
        ),
    ),
    Support.OUT_OF_SCOPE: (
        "Not something you ship to a page",
        (
            "Installs fine and is still the wrong tool here: a development dependency, or the "
            "server-side architecture this project is the alternative to. Listed because "
            "between them they are the most-downloaded packages in the survey, so "
            '"it installed" would otherwise read as an endorsement.'
        ),
    ),
}
"""Section title and preamble per verdict, in `SUPPORT_ORDER`."""


def _library_row(library: Library) -> str:
    """One table row. Downloads are shown because they are why the order is what it is."""
    version = f" {library.version}" if library.version else ""
    widgets = (
        f" Mounted: {', '.join(f'`{name}`' for name in library.widgets)}."
        if library.widgets
        else ""
    )
    guidance = f" **{_cell(library.guidance)}**" if library.guidance else ""
    downloads = f"{library.downloads:,}" if library.downloads else "-"
    return (
        f"| [`{library.distribution}`](https://pypi.org/project/{library.distribution}/)"
        f"{version} | {downloads} | {_cell(library.summary)} "
        f"| {_cell(library.observed)}{_cell(widgets)}{guidance} |"
    )


def _library_section(support: Support) -> list[str]:
    """One verdict class, or nothing if the registry has no entries in it."""
    entries = with_support(support)
    if not entries:
        return []
    title, preamble = SUPPORT_HEADINGS[support]
    return [
        f"## {title}",
        "",
        preamble,
        "",
        "| Distribution | Downloads/month | What it is | What the probe saw |",
        "|---|---|---|---|",
        *(_library_row(library) for library in entries),
        "",
    ]


def render_libraries() -> str:
    """Render the add-on support table as Markdown.

    Returns:
        The whole document, ending in a newline.
    """
    usable = sum(1 for library in LIBRARIES if library.usable)
    lines = [
        LIBRARIES_NOTICE,
        "",
        "# Library support",
        "",
        (
            f"{len(LIBRARIES)} Textual add-on libraries, probed inside Pyodide "
            f"{PYODIDE_VERSION} against Textual {MEASURED_AGAINST_TEXTUAL} on "
            f"{MEASURED_AT}. {usable} of them can be shipped to a browser today."
        ),
        "",
        (
            "Measured in four tiers, because no single one of them is a verdict: `micropip` "
            "install, import, this project's own static scan, and then the tier that actually "
            "decides a port - constructing every `Widget` subclass the library defines and "
            "mounting it in a running Textual app under the capture driver."
        ),
        "",
        (
            "Two results are worth reading before the table. On the first run of this survey "
            "the static scan produced **no findings at all**, across every library - which was "
            "a gap in the rules, not a clean bill of health. The two failures the runtime tier "
            "had already found showed where, and both now have registry entries that fire on "
            "the exact lines responsible. And the most-downloaded package here, "
            "`textual-serve`, installs and imports cleanly while being the one thing on this "
            "page you definitely should not use with it."
        ),
        "",
        ":::{warning}",
        (
            "**`textual[syntax]` does not install under Pyodide "
            f"{PYODIDE_VERSION}.** Textual's syntax extra needs `tree-sitter>=0.25.0`; Pyodide "
            "bundles 0.23.2 as a native wheel, which cannot be fetched from PyPI at another "
            "version. Found by way of `textual-textarea`, but not specific to it. micropip's "
            'message - "can\'t find a pure Python wheel for tree-sitter" - is misleading: it '
            "exists, one minor version too old."
        ),
        "",
        (
            "A plain `TextArea` was never affected. For highlighting the whole gap is one "
            "class, so `textual_wasm.treesitter` supplies it and "
            "`TextArea.code_editor(language=...)` works for the three grammars Pyodide "
            "bundles - **python, go and java**. Measured in Chromium and Firefox: 14 and 13 "
            "distinct colours painted, typing still reparsing, no console errors. The other "
            "twelve languages in the extra have no Pyodide recipe at all."
        ),
        ":::",
        "",
        (
            "Ordered by monthly PyPI downloads within each group, so the rows people are most "
            "likely to want come first. Run `textual-wasm doctor <module:App> -r <dist>` to "
            "check your own dependencies the same way."
        ),
        "",
    ]
    for support in SUPPORT_ORDER:
        lines += _library_section(support)
    lines += [
        "## What this does not tell you",
        "",
        (
            "- **WebKit is unmeasured.** It would not launch on the machine that ran these "
            "probes, so every verdict is Chromium and Firefox. See "
            "[browser support](browsers.md)."
        ),
        (
            "- **Mounting is not using.** A widget that mounts and renders can still fail on "
            "an interaction nobody drove. Libraries that reach the network (`textual-qrcode`, "
            "`textual-dad-joke`) or a real filesystem (`textual-fspicker`, "
            "`textual-universal-directorytree`) were mounted, not exercised end to end - and "
            "in a browser those two are exactly where CORS and MEMFS bite."
        ),
        (
            "- **Versions move.** Every row is one version on one date. A `textual_cap` verdict "
            "in particular is the most likely to be fixed by the library's next release."
        ),
        "",
    ]
    return "\n".join(lines) + "\n"
