"""The dependency set the WASM runtime must install, derived from the native environment.

The experiment compares two runtimes; it is only valid if both load the same code. micropip
resolves against Pyodide's own bundled package set before PyPI, so an unpinned install
silently produced a much older `rich` than the native environment had - and that older `rich`
imports `getpass`, hence `termios`, which failed an import-purity check for a reason
unrelated to either Textual or WASM.

Rather than hand-maintain a second version list that can drift out of agreement with
`poetry.lock`, the pins are *generated* from what is actually installed natively and written
to a committed file the JavaScript harness reads.
"""

from __future__ import annotations

import importlib.metadata
from pathlib import Path
from typing import Final

PINNED_DISTRIBUTIONS: Final[tuple[str, ...]] = (
    "textual",
    "rich",
    "markdown-it-py",
    "mdit-py-plugins",
    "platformdirs",
    "pygments",
    "typing-extensions",
    # pyte replays the emitted stream into a grid so the runtimes can be compared on what
    # they render, not only on the bytes they emit. Pure Python, as is its own dependency.
    "pyte",
    "wcwidth",
)
"""This package's complete runtime closure. All pure Python - nothing to cross-compile,
which is why the list can be installed under Pyodide at all."""

REQUIREMENTS_FILENAME: Final[str] = "wasm-requirements.txt"
"""Committed artifact read by `scripts/run_pyodide_node.mjs`."""


def resolve_pins() -> tuple[str, ...]:
    """Return `name==version` for each distribution, as currently installed natively.

    Raises:
        importlib.metadata.PackageNotFoundError: If a listed distribution is not installed,
            which means the native environment cannot define the WASM one.
    """
    return tuple(f"{name}=={importlib.metadata.version(name)}" for name in PINNED_DISTRIBUTIONS)


def write_pins(path: Path) -> tuple[str, ...]:
    """Write the resolved pins to `path`, one per line, and return them."""
    pins = resolve_pins()
    header = (
        "# Generated by `textual-wasm-spike pins`. Do not edit by hand.\n"
        "# Mirrors the native environment so the two probe runs load identical code.\n"
    )
    path.write_text(header + "\n".join(pins) + "\n", encoding="utf-8")
    return pins
