/* Generated by `textual-wasm channels`. Do not edit.
 *
 * The channel names and payloads below come from one declaration in Python, so this file and
 * the application cannot disagree about what a channel carries. Regenerate after changing
 * that declaration; `--check` fails a build when this file is stale.
 */

export type LevelName = "gain" | "bass" | "treble";

export interface Clipping {
  threshold: number;
  hot: LevelName[];
}

/** Every channel this application declares, and what it carries. */
export interface Channels {
  gain: number;
  bass: number;
  treble: number;
  clipping: Clipping;
  note: string;
}

export type ChannelName = keyof Channels;

/** What `textual_wasm.bridge.Codec` is on this side. */
export interface Codec {
  encode(value: unknown): string;
  decode(text: string): unknown;
}

export interface Bridge {
  /** Encode with the codec and send. The payload type follows from the channel name. */
  send<K extends ChannelName>(channel: K, value: Channels[K]): void;
  /** Send as-is, with no codec in the way. Any name: the pipe has no schema. */
  sendText(channel: string, text: string): void;
  /** Receive decoded. Returns an unsubscribe function. */
  on<K extends ChannelName>(channel: K, callback: (value: Channels[K]) => void): () => void;
  /** Receive raw. Returns an unsubscribe function. */
  onText(channel: string, callback: (text: string) => void): () => void;
  codec: Codec;
}

export interface Screen {
  columns: number;
  rows: number;
  lines: string[];
}

/** Published on `globalThis` once the application is driving the terminal, not before. */
export interface TextualWasm {
  columns: number;
  rows: number;
  worker: boolean;
  finished: Promise<unknown>;
  /** Keystrokes, as if typed. For control; use `bridge` for values. */
  input(data: string): void;
  screen(): Screen;
  bridge: Bridge;
}

declare global {
  // Optional, and that is the contract rather than caution: it appears seconds after the
  // page does, so a page must wait for it.
  // eslint-disable-next-line no-var
  var textualWasm: TextualWasm | undefined;
}
